#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapi-deployment
spec:
  selector:
    matchLabels:
      app: nodeapi-server
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapi-server
    spec:
      containers:
      - name: nodeapi-container
        #image: gcr.io/tensorflow-serving/resnet
        image: docker.io/luiscocotleuv/apicv:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nodeapi-service
  name: nodeapi-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: nodeapi-server
  type: LoadBalancer